### ISSUE TITLE
Suggestion to publish through Nuget

### ISSUE THREAD

**Issue by DaveInCaz** [wfletcher/EasyGIS.NET#10]
I noticed there was an EasyGIS package on Nuget:

https://www.nuget.org/packages/Huitian.EGIS.ShapeFileLib/

but based on the author's name & the age of the package, I'm guessing it might not be officially affiliated with this project. (Not that there is anything wrong with that package as far as I can see, but I didn't look closely). 

Interestingly it shows nearly 13K downloads, which I think is an indicator in the amount of interest in this project!  I have been using it from source (added the project to my solution) which works but a Nuget package would be a lot more convenient - saving build time and also alerting (in a sense) when updates become available.

That said, I don't know how much work it is to publish that way, so maybe this is asking a lot...

**Comment by DaveInCaz** [comment]
Oh, I see this was mentioned once before in a closed issue (actually a comment on a PR) 
 https://github.com/wfletcher/EasyGIS.NET/pull/4

**Comment by apolloLegends** [comment]
I have the same request.

**Comment by wfletcher** [comment]
The nuget package you mentioned was put up by someone else and I'm not sure which version it was,  but I suspect it's quite old.

I'll try and release an official nuget package soon.

**Comment by wfletcher** [comment]
NuGet packages have now been published for latest release (v4.8.0). See #57 for more details
