### ISSUE TITLE
Create shapefiles and open as Stream without save

### ISSUE THREAD

**Issue by theo2f** [wfletcher/EasyGIS.NET#11]
Until today I only worked with maps that I created, saved and then opened.
My idea is to create maps and load them, without saving them. I think I would have better management of these temporary maps that today I create, save and open.
I used the example of stream in MainForm.cs and it worked correctly. However, that example duplicates a loaded map. I was unable to change it to create a map and leave it in memory, then load it from the stream.
It would be great if there was a method to create shapefiles of lines, points and polygons and leave them in memory, or even load them on the map.

**Comment by wfletcher** [comment]
The Shapefile class has methods to open from separate streams for the .shp .shx .dbf etc. the original reason for adding this was twofold - there is a performance gain in some scenarios, and in other cases it allows opening a shapefile from sources such as a zip file, web server upload stream or aws s3 bucket without the need to save it to disk first.

In the case you mentioned you could use a shapefilewriter (which also has methods to write to a stream) and then create a shapefile from the streams and load in a map.

I am working on an example to do this and will upload soon

**Comment by DaveInCaz** [comment]
Another very handy use of the stream reading is to open data files which are embedded assembly resources, which works great. My app mixes some files from resources with other streams it creates on the fly and they all render together.

**Comment by wfletcher** [comment]
I've uploaded an example to the easygisdotnet.com website showing how to create a shapefile using MemoryStreams and then load it on a map without saving to disk. The example is available on the [code examples page](https://www.easygisdotnet.com/code-examples.html)

[direct link](https://www.easygisdotnet.com/downloads/EGISCodeSnippets.zip)
