### ISSUE TITLE
Getting IO Stream from SHP Created from Memory Streams

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#113]
I would like to know how to create DBreader from **Shape File** that was created from memory streams.
I could seek the database where Streams are saved as a **byte array** in the first place.
Just not sure how to convert IO.MemoryStream to IO.Stream avoiding writing **byte array** to a dbf file.

However, could a **Shape File** be used as a Source of IO.stream
![image](https://user-images.githubusercontent.com/26789352/234339720-fbfc5ff0-a27c-42ae-8c59-c35a0a59f1bd.png)

**Comment by wfletcher** [comment]
IO.MemoryStream inherits from IO.Stream so you do not need to convert anything.

var dbReader = new DbfReader(yourMemoryStream)

**Comment by wfletcher** [comment]
If you created the ShapeFile from memory streams then you would already have a reference to the stream. If you create the shapefile from a file path then you can just create a new FileStream from the Dbf file path

**Comment by dusko23** [comment]
Currently, I do not keep a track record of memory streams.
I create streams from scratch or read from the db, create the shape file, and forget about streams.
I can think of introducing the list of the following structure

- shp_uniqueID
- 4x memory streams

Question:
when a particular shape file is created from the structure above, does the library create a copy of the streams or just use the reference?

**Comment by wfletcher** [comment]
If you want the DbfReader for the ShapeFile you know there is a ShapeFile.DbfReader property that returns the DbfReader that the shapefile creates when it is initialized?

**Comment by dusko23** [comment]
Thanks.
One question:
If I keep a reference to the DBF stream and at some point change the content of the DBF stream, like new columns with new values, would that work without recreating the shape file from the streams?

**Comment by wfletcher** [comment]
No that will not work. Consider the ShapeFile as read only

**Comment by DaveInCaz** [comment]
How does shapeFile.DbfReader differ from shapeFile.RenderSettings.DbfReader?

**Comment by wfletcher** [comment]
@DaveInCaz the ShapeFile's DbfReader is passed to the constructor of the RenderSettings when it is created and is a reference to to the ShapeFile.DbfReader. The 2 methods will return a reference to the same DbfReader object
