### ISSUE TITLE
Disabling Mouse Wheel

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#114]
I have a scenario where I need to disable SFmap to respond to MouseWheel Event.
Even if I put an immediate Exit Sub in MouseWheel Event, the shape file is zoomed in/out.
During MouseWheel I compose backdrop raster maps from various sources which occasionally takes time.
How do I prevent SFmap from performing zoom in/out while composing a raster map?

**Comment by wfletcher** [comment]
I would suggest looking at the SFMap code and see if there is a MouseWheelZoomMode property

**Comment by wfletcher** [comment]
![image](https://user-images.githubusercontent.com/12992602/235273370-c28a5f82-8a5f-4de6-a06f-e347a1312b4f.png)

![image](https://user-images.githubusercontent.com/12992602/235273380-8d756f52-048f-4ce4-b7c9-49bad6d6e98b.png)

**Comment by dusko23** [comment]
I tried that but the raster map and shape file are not aligned properly after hasty zooming in/out is settled.
**MouseWheel** event starts with setting **MouseWheelMode** = **Disabled**
and exists with **MouseWheelMode** = **Default**

However, I found a rock-solid solution.
Variable **DisableSFmapActivity** is defined.
When the **MouseWhell** event triggers it is set to **True** and to **False** on exit.
Events **Pain** and **PaintMapBacgroud** exit immediately if **DisableSFmapActivity**  = **True**
