### ISSUE TITLE
Disabling Refresh in General

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#115]
I did some tests, and it appears that the library performs a full refresh after removing the shape file from the SFmap object.
In general, that makes sense. However, there are real-world scenarios where adjusted logic would help a lot.

**Scenario**
I manage many layers of shape files (file and memory-based) as a Project.
On top, I manage many concurrent Projects. All are displayed on a single SFmap object.

**Suggestion**
In order to optimize user experience it would be just excellent to introduce something like **DisableRefresh** property of the SFmap object which disables any refresh if set to **True**.

This enables the manipulation of shape files without refreshing.
Visibility (shp or record level), shp added, removed,  changing shp renderer.

When Pan or Zoom happens **DisableRefresh** is set to **False** by internal logic.
**DisableRefresh**  can also be set to **False** programatically.
**DisableRefresh** default value is **False**.
I would really like to hear your opinion about my suggestion.

**Comment by wfletcher** [comment]
I will have a look at adding BeginUpdate / EndUpdate methods similar to the ListBox control. If BeginUpdate is called all drawing will be disabled until EndUpdate is called.

**Comment by dusko23** [comment]
Thanks for that. It would really make a change to the user experience.
The nice thing is that my logic does not need to change.
Just calling methods on both ends of the flow is required.
I'm really looking forward to a new release.

**Comment by wfletcher** [comment]
BeginUpdate EndUpdate methods added to SFMap control to disable drawing while adding/removing shapefiles

**Comment by dusko23** [comment]
Great news :-)
Just checked and it appears that it is not available via nuget.
![image](https://github.com/wfletcher/EasyGIS.NET/assets/26789352/a017ca11-2bb9-474f-bcaf-095c9a4647c8)
Or it is updated within the same version?
If that is the case should I uninstall and install again?

**Comment by wfletcher** [comment]
The changes have been committed but not released yet. If you want to try out the changes then you will need to download the latest source code and build it.

**Comment by dusko23** [comment]
Will wait until released. Any idea about when? Building a c# project is not my cup of tea although I would love to do it.

**Comment by wfletcher** [comment]
Can't give an exact date on when the next release will be. 
Building the project is not hard, as there are not any dependencies other than a few nuget packages. Download the source code, open the EasyGISDesktop.sln file and click Build Solution

**Comment by dusko23** [comment]
That I can try.
Please, just tell me which files to copy from where to where after the solution is built.
I hope that the nuget checker will not complain that there are some irregular components inside my solution.
