### ISSUE TITLE
sfMap Disable Line Labels 

### ISSUE THREAD

**Issue by blinkor** [wfletcher/EasyGIS.NET#17]
When I use example 5 from the EasyGIS examples for desktop in ``c#`` and load a custom ``shapefile``, line labels often show up. How do I disable these? 
![image](https://user-images.githubusercontent.com/66094636/119420554-fb898f00-bcb9-11eb-8b3b-545cfc1c2652.png)

**Comment by wfletcher** [comment]
If you have a look in the OpenShapefile method you will see a comment - 

// read the shapefile dbf field names and set the shapefiles's RenderSettings
// to use the first field to label the shapes.

Uncomment the line or set the FieldName to be an empty string to stop the labels being displayed

sf.RenderSettings.FieldName = ""



 private void OpenShapefile(string path)
        {
            // clear any shapefiles the map is currently displaying
            this.sfMap1.ClearShapeFiles();
            
            // open the shapefile passing in the path, display name of the shapefile and
            // the field name to be used when rendering the shapes (we use an empty string
            // as the field name (3rd parameter) can not be null)
            this.sfMap1.AddShapeFile(path, "ShapeFile", "");
            
            // read the shapefile dbf field names and set the shapefiles's RenderSettings
            // to use the first field to label the shapes.
            EGIS.ShapeFileLib.ShapeFile sf = this.sfMap1[0];
            sf.RenderSettings.FieldName = sf.RenderSettings.DbfReader.GetFieldNames()[0];
        }

**Comment by blinkor** [comment]
Also, if I want to make the map lines and the actual map's "object" or land a specific BackColor, will I have to create a ``ICustomRender`` type of class?

**Comment by wfletcher** [comment]
Yes you will need to create a class that implements ICustomRenderSettings or extend from BaseCustomRenderSettings. Example 8 on the easygis.net website  would be a good place to look for examples of this.
