### ISSUE TITLE
System.OutOfMemoryException Error in EGIS.ShapeFileLib.dll

### ISSUE THREAD

**Issue by blinkor** [wfletcher/EasyGIS.NET#18]
Hello, I've been receiving this error for the past few days. (Note: Example 5 works by itself).

I've been trying to implement example 5 into another .NET application language (``VB.NET``) but I've received the error:
```
Exception thrown: 'System.OutOfMemoryException' in EGIS.ShapeFileLib.dll
An unhandled exception of type 'System.OutOfMemoryException' occurred in EGIS.ShapeFileLib.dll
```

I'm not sure whats going on, as I believe I imported all libraries correctly. Is there any libraries/other files in the Example 5 source code (other then the DLLs) that are required to be imported? I don't understand why this is happening.

I render my shapefile like this:

```
 SfMap1.ClearShapeFiles()
  SfMap1.AddShapeFile("C:\Users\admin\assets\boundry.shp", "ShapeFile", "")
```

**Comment by wfletcher** [comment]
Can you upload your solution somewhere? There’s many reasons why an OutOfMemoryException can be thrown

**Comment by blinkor** [comment]
I think I found out the error, I believe it was because ``Proj6`` folder was not in debug and ``DBF`` files were not imported correctly. However, I've been trying out ``CustomRender`` settings from the previous question. Is there a simpler way to color *all* lines on the shapefile a specific color & filling all areas within the shape files a specific color? Thanks!

**Comment by wfletcher** [comment]
If you want to color all records a specific color use the ShapeFile.RenderSettings.OutlineColor and ShapeFile.RenderSettings.FillColor to fill all records with a specific color.

The ICustomRenderSettings should be used if you need to render specific records in a different color. You can also write a class that extends from BaseCustomRenderSettings - this class implements ICustomRenderSettings, uses default RenderSettings and you can override specific ICustomRenderSettings methods if needed.
