### ISSUE TITLE
Plotting large amounts of points in SfMap Unexpected Results

### ISSUE THREAD

**Issue by blinkor** [wfletcher/EasyGIS.NET#20]
I'm trying to plot a large amount of points into a ``SfMap`` control. I have around 600+ points listed in a CSV file.
The points are listed by their longitude/latitude in a csv file.

I created a list of points which I draw onto my ``SfMap`` with a ``for`` loop. However, when I expect to see all 600 points plotted, I only see 30-40 actually shown on the map, in a grid-like pattern. It doesn't matter how much I zoom into the map, there are the same amount of dots. My longitude and latitude are very precise in the CSV file, with 600+ individual points (such as ``131.6958, 32.506``). Although it takes on the general shape I am going for, it is not plotting all points. I'm sure this isn't an issue with the shapefile itself, as I've tried multiple ones. 

I know this isn't an issue with the way I import the points into a list, I've checked. 

I think this may be an issue on the ``SfMap1.GisPointToPixelCoord`` function. 

I checked the individual X, Y positions after the point conversion, they do account for zoom but they somehow don't account for all of the points. (There are 25 different longitude/latitude converted into the same X/Y, regardless of zoom).

The code looks like this:
```
'Loop in the SfMap's paint event.

 For Each str As Tuple(Of String, String, Point, Point) In apiTimer.initialLocationDB
'The fourth Point variable stores the longitude/latitude data.
'I know there isn't anything wrong with the Tuple.

            Dim pt As Point = Me.SfMap1.GisPointToPixelCoord(str.Item4.X, str.Item4.Y) 'Convert the Long/Lat to a Point

            'Marker is then drawn using default function shown in an example.
        Next
```

The output, somehow turning 600 points to only 30-40. Is there some limitation to the points drawn on the SfMap?
![image](https://user-images.githubusercontent.com/66094636/126054356-454831c5-82db-4e01-bca8-a2bd7a1ebea8.png)

**Comment by wfletcher** [comment]
Can you upload the csv data file?

**Comment by wfletcher** [comment]
You could also try add XY data using easygis.net desktop and see if the results look similar

**Comment by blinkor** [comment]
It works in the EasyGIS Desktop App. It doesn't work In my application.

LOAD SHAPEFILE:
```
 Dim colors As Dictionary(Of String, Color) = New Dictionary(Of String, Color)()
        '
        SfMap1.AddShapeFile("C:\Users\admin\shapefile.shp", "ShapeFile", "")
        SfMap1(0).RenderSettings.FillColor = Color.FromArgb(42, 44, 47)
        SfMap1(0).RenderSettings.LineDashStyle = Drawing2D.DashStyle.Solid
        SfMap1(0).RenderSettings.MaxZoomLevel = 10000000
        SfMap1(0).RenderSettings.OutlineColor = Color.DimGray
        SfMap1(0).RenderSettings.MinZoomLevel = 1
```

DRAW POINTS:
```
  For Each str As Tuple(Of String, String, Point, Point) In pointClass.tuple
            Dim pt As Point = Me.SfMap1.GisPointToPixelCoord(str.Item4.X, str.Item4.Y) 'Long/Lat is located as a point variable in Item4 of the tuple.

            DrawMarker(e.Graphics, pt.X, pt.Y) 'Function to draw marker:
        Next
```

CUSTOM FUNCTION:
```
Public Sub DrawMarker(ByVal g As Graphics, ByVal locX As Double, ByVal locY As Double)
 Dim myRectangle As New Rectangle
                Dim rectHeightHalf As Integer = rectH / 2
                Dim rectWidthHalf As Integer = rectW / 2
                '    Dim pt As Point = Me.SfMap1.GisPointToPixelCoord(locX, locY)
                g.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias
                myRectangle.X = locX - rectWidthHalf
                myRectangle.Y = locY - rectHeightHalf
                myRectangle.Width = rectW
                myRectangle.Height = rectH

                g.FillEllipse(blueBrush, myRectangle)
End Sub
```

Download CSV/Shapefile (Long/Lat is located in last 2 columns).
[Download Here](https://drive.google.com/drive/folders/1zZ9SVPS7WZ61ZJ6ODZvliSsCsPmXC0cr?usp=sharing)

**Comment by wfletcher** [comment]
I think your issue might be because of how you are storing your points read from the csv data file.

For Each str As Tuple(Of String, String, Point, Point) In pointClass.tuple

Point is a System.Drawing.Point, which uses integer coordinates and not double precision coordinates. I would suggest using the EGIS.ShapeFileLib.PointD structure to store the points read from the CSV file.

Here is the map when I read and draw the double precision points.
![image](https://user-images.githubusercontent.com/12992602/126084583-6f22b723-0679-4314-9533-4f5141d2a47a.png)

and the C# code to read and draw the points. 
`private List<PointD> points = new List<PointD>();

		private List<PointD> LoadcsvFile(string path)
		{
			List<PointD> pts = new List<PointD>();
			using (System.IO.StreamReader reader = new System.IO.StreamReader(path))
			{
				string nextLine = null;
				while ((nextLine = reader.ReadLine()) != null)
				{
					string[] tokens = nextLine.Split(',');
					double lat, lon;
					if (double.TryParse(tokens[tokens.Length - 2], System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out lon) &&
						double.TryParse(tokens[tokens.Length - 1], System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out lat))
					{
						pts.Add(new PointD(lon, lat));
					}
				}
			}
			return pts;
		}


		public void DrawMarker(Graphics g, int locX, int locY)
		{
			const int rectH = 6;
			const int rectW = 6;

			Rectangle myRectangle = new Rectangle();
			int rectHeightHalf = rectH / 2;
			;
			int rectWidthHalf = rectW / 2;

				//    Dim pt As Point = Me.SfMap1.GisPointToPixelCoord(locX, locY)

			g.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias;
			myRectangle.X = locX - rectWidthHalf;
			myRectangle.Y = locY - rectHeightHalf;

			myRectangle.Width = rectW;

			myRectangle.Height = rectH;


			g.FillEllipse(Brushes.Blue, myRectangle);
		}

		private void sfMap1_Paint(object sender, PaintEventArgs e)
		{
			foreach (var point in points)
			{
				var pixelPoint = sfMap1.GisPointToPixelCoord(point);
				DrawMarker(e.Graphics, pixelPoint.X, pixelPoint.Y);// 'Function to draw marker:
			}
		   
		}`

**Comment by blinkor** [comment]
The issue was storing the values in a integer-based point variable. Thanks!
