### ISSUE TITLE
Custom labels

### ISSUE THREAD

**Issue by theo2f** [wfletcher/EasyGIS.NET#21]
Hi Winston!
Can you provide a example for custom labels?
Thank you!

**Comment by wfletcher** [comment]
I've updated the code snippets example with a simple custom labels example.
https://www.easygisdotnet.com/code-examples.html

The easiest way to create your own custom labels is to create a class that inherits BaseCustomRenderSettings and then override UseCustomRecordLabels and GetRecordLabel

`#region custom labels

		private void LoadCustomLabelsExample()
		{
			string worldShapefilePath = System.IO.Path.Combine(Application.StartupPath, "data/world_adm0.shp");
			var shapefile = sfMap3.AddShapeFile(worldShapefilePath, "world", "", false);
			shapefile.RenderSettings.Font = new Font(this.Font.FontFamily, 12);
			shapefile.RenderSettings.CustomRenderSettings = new CustomLabelRenderSettings(shapefile.RenderSettings);
		}

		/// <summary>
		/// simple ICustomRenderSetgings class that creates record labels using all attributes
		/// </summary>
		private class CustomLabelRenderSettings : EGIS.ShapeFileLib.BaseCustomRenderSettings
		{
			public CustomLabelRenderSettings(EGIS.ShapeFileLib.RenderSettings renderSettings) :
				base(renderSettings)
			{

			}

			public override bool UseCustomRecordLabels
			{
				get { return true; }
			}

			public override string GetRecordLabel(int recordNumber)
			{
				//return all of the record attributes separated by newline
				string[] recordAttributes = base.renderSettings.DbfReader.GetFields(recordNumber);

				string label = string.Join("\n", recordAttributes);
				return label;
			}
`
