### ISSUE TITLE
SFMap Converting Distance to Pixel Points 

### ISSUE THREAD

**Issue by blinkor** [wfletcher/EasyGIS.NET#30]
Extending on the topic of drawing custom objects on the SFmap control with the paint event, is there a way to convert a distance (of KM) to the number or length of pixel points of a current SFmap control? Is there a function that does this?

I’m trying to do this, but I have to convert one random longitude and latitude point to a SFmap pixel point, choosing another random longitude and latitude point exactly that amount of KM away, and converting that to a SFmap pixel point, finally subtracting the distance between the two pixel points to get a relative distance from KM to SFmap pixels, is there another easier way to do this? (The functions mentioned here are https://easygis.net/api/output/html/M_EGIS_Controls_SFMap_GisPointToPixelCoord_1_cfca3a5a.htm)

I didn’t find a function for doing this in the SFmap reference, and I don’t have a working method for doing my method (in the second paragraph with .NET anyways). Is there a way I can do this with SFmap (converting distance in KM to number of pixel points) or using my method described in the second paragraph?

Any help would be appreciated!

**Comment by wfletcher** [comment]
Your best bet to do this is to use a projected coordinate system and then you can just use the SFMap.ZoomLevel property to convert between pixels and map coordinates.  ZoomLevel is basically 1/scale. If you're not sure which projected coordinate system to use you can always use Web Mercator Projection (EPSG 3857) , but be aware that the distances may be distorted if your map area is close to the earth's poles. You could also use UTM coordinates 

If you have to use lat/lon geodetic coordinates you can calculate the distance between the coordinates at the top left map coordinate and the bottom right coordinate. From this you can calculate the approximate number of pixels per meter.
This is sample code I use to calculate the distance between 2 points on the SFMap control.

```
        private double DistanceBetweenPoints(PointD p0, PointD p1)
        {
            double distance = double.NaN;
            if ((this.MapCoordinateReferenceSystem as IGeographicCRS) != null)
            {
                distance = EGIS.ShapeFileLib.ConversionFunctions.DistanceBetweenLatLongPointsHaversine(ConversionFunctions.Wgs84RefEllipse, p0.Y, p0.X, p1.Y, p1.X);
            }
            else if ((this.MapCoordinateReferenceSystem as IProjectedCRS) != null)
            {
                //calculate euclidean distance
                distance = Math.Sqrt((p1.X - p0.X) * (p1.X - p0.X) + (p1.Y - p0.Y) * (p1.Y - p0.Y));
            }
            return distance;
        }
```

**Comment by blinkor** [comment]
Okay, I tried this, giving two sample points.

Main Function (where ``SfMap1`` is a SFMAP Control):
```
Private Function DistanceBetweenPoints(ByVal p0 As PointD, ByVal p1 As PointD) As Double
        Dim distance As Double = Double.NaN

        If (TryCast(Me.SfMap1, IGeographicCRS)) IsNot Nothing Then
            distance = EGIS.ShapeFileLib.ConversionFunctions.DistanceBetweenLatLongPointsHaversine(ConversionFunctions.Wgs84RefEllipse, p0.Y, p0.X, p1.Y, p1.X)
        ElseIf (TryCast(Me.sfmap1, IProjectedCRS)) IsNot Nothing Then
            distance = Math.Sqrt((p1.X - p0.X) * (p1.X - p0.X) + (p1.Y - p0.Y) * (p1.Y - p0.Y))
        End If

        Return distance
    End Function
```

I'm trying to find the distance between two sample points when a shapefile is loaded like this:
```
Dim a1 As New PointD(35.652832, 139.839478)
Dim a2 As New PointD(34.672314, 135.484802)
MsgBox(DistanceBetweenPoints(a1, a2))
```

I still get ``NaN`` as the distance for some reason. Do you know what the issue is?

**Comment by wfletcher** [comment]
A couple of things ..
You’re trying to cast Me.SfMap1 to a CRS - not familiar with vb.net but I think you mean to cast Me.SfMap1.MapCoordinateReferenceSystem To IGeographicCRS.

secondly the PointD coordinates should be specified in X,Y order which is Lon,Lat.
Try 
Dim a1 As New PointD(139.839478, 35.652832) ..

**Comment by blinkor** [comment]
I tried this function, casting to the CRS as mentioned. I also reversed the coordinate points so that they are correct.

```
    Private Function DistanceBetweenPoints(ByVal p0 As PointD, ByVal p1 As PointD) As Double
        Dim distance As Double = Double.NaN

        If (TryCast(Me.SfMap1.MapCoordinateReferenceSystem, IGeographicCRS)) IsNot Nothing Then
            distance = EGIS.ShapeFileLib.ConversionFunctions.DistanceBetweenLatLongPointsHaversine(ConversionFunctions.Wgs84RefEllipse, p0.Y, p0.X, p1.Y, p1.X)
        ElseIf (TryCast(Me.SfMap1.MapCoordinateReferenceSystem, IProjectedCRS)) IsNot Nothing Then
            distance = Math.Sqrt((p1.X - p0.X) * (p1.X - p0.X) + (p1.Y - p0.Y) * (p1.Y - p0.Y))
        End If

        Return distance
    End Function
```

This does not seem to calculate the map correctly, even at a zoom level at one (I'm assuming the value produced from the function - the pixel length is way too far). I also want to be able to account for zoom, so do I have to do some other operation with ``distance`` returned from the function with the ``ZoomLevel`` of the SFmap? Thank you for your help..

**Comment by wfletcher** [comment]
If the SFMap is using a projection you can get the VisibleExtent and divide the extent width by the controls ClientWidth - this should give you metres/pixel.
If the map is using geographic coordinates you can get the VisibleExtent and pass the top left and top right points of the extent to your distance function and divide the result by the client width.

note that the result may not be accurate if you’re nit using a projection.

https://www.easygisdotnet.com/api/output/html/P_EGIS_Controls_SFMap_VisibleExtent.htm
