### ISSUE TITLE
Disabling Mouse Wheel Impact on SFmap Object

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#39]
I am using the mouse wheel for editing purposes as well.
For example, to rotate a text before placing it on a map.
Is there a way to disable Zooming?
I managed to compensate Zooming effect but it requires a full refresh.
Regards

**Comment by dusko23** [comment]
I found a solution how to manage MouseWheel Event.
However, it would need to copy and paste a lot of code because the current implementation uses SFmap object added in design time. A  Simper solution is highly appreciated.

![CaptureIgnoreMwheel](https://user-images.githubusercontent.com/26789352/158491950-23401b1f-2010-4e8e-bded-462f2edde7e0.PNG)

**Comment by wfletcher** [comment]
I will add an option the the SFMap control to control MouseWheel Zooming.

**Comment by dusko23** [comment]
Great, thanks.

**Comment by wfletcher** [comment]
use SFMap.MouseWheelZoomMode property to control mouse wheel zoom. three options available - 
Default (current functionality)
Reverse the controls
Disabled: mouse wheel zooming is disabled

**Comment by dusko23** [comment]
Tried that, but it appears it has not been implemented yet.
Or is it notice in advance :-)

![image](https://user-images.githubusercontent.com/26789352/158913380-b83410f1-3bac-4c96-a554-ef0bb7b86e60.png)
![image](https://user-images.githubusercontent.com/26789352/158913474-c6b86267-14d5-4a09-89e8-11f823112995.png)
