### ISSUE TITLE
Docking SFmap

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#45]
I have an issue docking SFmap object between Menu Strip (on the top) and Status Strip (at the bottom). Tried all imaginable tricks found on Stackoverflow and elsewhere. I would like to place SFmap properly between Menu and Status Strip. Tried to use a panel as well.
But nothing works. The best outcome is proper docking in relation to Menu Strip. But SFmap always "goes" behind Status Strip and spans to Form bottom. Docking in runtime does not help either.  Bringing to front and sending to back has no satisfactory effects. In design and in runtime alike. There are some indications that this is a Microsoft bug that lasts for ages. I am using VS 2017.
Any idea perhaps?

**Comment by gregdriver** [comment]
Hi s, zzz

**Comment by wfletcher** [comment]
Sorry - Can't reproduce this. 

Example1 on easygis.net website docks the SFMap on a form and works as expected.

https://www.easygisdotnet.com/downloads/Example1.zip

**Comment by dusko23** [comment]
I think it is a Microsoft bug. It is an indication from others as well. Moderate GUI implementation with little changes causes no docking problem. Changing GUI a lot can create a GUI constellation where docking of certain objects is suddenly out of full controll.
