### ISSUE TITLE
PolygonZ Shape File Findigs

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#47]
**PolygonZ** type (supported by Egis Library)  
raises and Error when calling the following function on  PolygonZ shape file.
![image](https://user-images.githubusercontent.com/26789352/159926632-f283fc66-d08d-476e-94ef-f34ac9cc031c.png)

The following error is shown
**The method or operation is not implemented.**

**Comment by wfletcher** [comment]
This is a duplicate of #38 and has been fixed. You can download the latest source code or wait for the next release

**Comment by wfletcher** [comment]
duplicate. Closing

**Comment by dusko23** [comment]
Thanks for the update Winston, will wait for a new release. Cany you please
give an estimate of when it might be released and will the mouse wheel be
under developer control as well?
Regards, Dusan
