### ISSUE TITLE
2 Points Horizontal Polyline Disappears When SFmap EPSG is Changed

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#48]
**Step 1:**
SFmap contains raster map EPSG 3912
The following Shp files are created:
- Red Point Number 0,
- 2 points Polyline.

2 points polyline represents distance leg created in Orthogonal Mode. The Left and right Y coordinates are identical.
Labeled by magnetic north declination, leg length, and the sum of previous legs lengths.
![image](https://user-images.githubusercontent.com/26789352/160257396-2af10978-18d9-44f2-b8f9-1b742414680c.png)

**Step 2:**
Switching the raster map from EPSG 3912 to Web Maps (Pseudo Mercator), Polyline disappears. Red Point remains.
![image](https://user-images.githubusercontent.com/26789352/160257481-335faf7d-e823-4f89-a80e-c1e9951169c2.png)

**Step 3:**
Switching back to the raster map EPSG 3912 polyline reappears.
![image](https://user-images.githubusercontent.com/26789352/160257517-108c9032-db1d-449f-ad08-5d51a0efba28.png)

**Step 4:**
 Slanted polyline performs as expected.
![image](https://user-images.githubusercontent.com/26789352/160257556-069ff789-c42c-4267-8732-c36ba4c3a36e.png)
![image](https://user-images.githubusercontent.com/26789352/160257575-fdad9d43-a34f-4672-a01d-cec339ef6729.png)

**Comment by wfletcher** [comment]
Without more information can't reproduce this. Please upload sample shapefile

**Comment by dusko23** [comment]
The zip file contains two shapefiles.
Each has two vertices.
One is horizontal and one is slanted.
Just drag-drop into Egis Desktop.
Slanted will show, horizontal will not,
The thing is that horizontal is actually added to the SFmap object, but it is not shown.
[SHPtest.zip](https://github.com/wfletcher/EasyGIS.NET/files/8404100/SHPtest.zip)
The length of each is about 49 meters.
Hope this helps.

**Comment by wfletcher** [comment]
Bug appears to be due to the shapefile having a bounding box with a height of zero. Will need to investigate further

**Comment by dusko23** [comment]
Horizontal 2 vertices polyline is drawn by adding/removing shapefiles to/from SFmap object.
Interestingly enough polyline shows up after creation but "visibly disappears" when SFmap EPSG is changed. However, the polyline is there (coordinates are correct (using my shapefile checked tool)).
When the file is created from MemoryStreams writer probably writes Boundary Rectangle into Headers.
If Height is Zero (my case) then writing epsilon instead of 0 might be an acceptable solution.
The same might apply to Width.
I think that the Boundary Box of any object in a GIS system can not have a boundary rectangle width or height = 0. If something exists in the real world it must have an area >0. Even if it is a polyline or point.

**Comment by wfletcher** [comment]
A bounding box with a zero width or height is still valid and a single point would have a bounding box of zero width and height. This is a bug and needs to be fixed

**Comment by wfletcher** [comment]
This has been fixed and will be available in next release or grab latest code for changes

**Comment by dusko23** [comment]
Thanks, Winston, any idea about when the new release might be released?
