### ISSUE TITLE
Bound CRS not identified when loading from WKT

### ISSUE THREAD

**Issue by wfletcher** [wfletcher/EasyGIS.NET#53]
When the Proj CRS type is PJ_TYPE_BOUND_CRS the EPSG Id is not identified when loading from WKT.

An example CRS is Slovenia 1996 / Slovene National Grid (EPSG ID 3794).

**Comment by wfletcher** [comment]
To obtain the Id after the bounds CRS is loaded from WKT the source CRS needs to be loaded to obtain the ID.

```
// CRS loaded from WKT and stored in 'p'
IntPtr srcCrs = Proj6Native.proj_get_source_crs(context, p);

authName = Proj6Native.GetAuthName(srcCrs);
id = Proj6Native.ProjGetIdCode(srcCrs);

```

**Comment by dusko23** [comment]
Not sure what actually to do if
![image](https://user-images.githubusercontent.com/26789352/162053328-5dfb3183-ca7f-4fa5-b0dc-8b0bc3a73213.png)
CoordinateReferenceSystem is **ReadOnly** Property.
![image](https://user-images.githubusercontent.com/26789352/162053710-56f7c7d5-f0e5-4c0a-97f0-d3b76da81fc4.png)
Note: myPROP is shp Tag Object to hold necessary data including binary serialized rendeder.

**Comment by wfletcher** [comment]
Fixed in version 4.8.0

**Comment by dusko23** [comment]
Great Winston, any suggestions on when 4.8 will be released. I currently
have some developments in halt as can not continue without it working?

**Comment by wfletcher** [comment]
Version 4.8.0 has been released. The easiest way to upgrade your project is to install the new NuGet packages.

https://www.easygisdotnet.com/install-nuget-packages.html

As you already have references to the EGIS libraries you only need to perform step 1 and 2
