### ISSUE TITLE
Projects csproj upgraded to new SDK format

### ISSUE THREAD

**Issue by wfletcher** [wfletcher/EasyGIS.NET#56]
To enable easier creation of nuget packages and support .net6-windows the older style csproj files will be upgraded to the newer SDK style csproj.

This will be a first step before creating nuget packages for easier integration into other projects

**Comment by DaveInCaz** [comment]
Do you know what versions of .NET and Visual Studio these new projects will still be compatible with?

**Comment by wfletcher** [comment]
I’ve tested with visual studio 2019 and 2022

**Comment by wfletcher** [comment]
I’m still targeting .net 4.7 so existing projects using the library will still work if you are using .net 4.7 or higher

**Comment by wfletcher** [comment]
Fixed in 4.8.0
