### ISSUE TITLE
GetClosestShape Suggestion

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#60]
It is great to have Source ICRS implemented inside GetClosestShape .
This enables to filter out detecting SHP files with similar numerical values but different ICRS. Just great.

It would be equally great to add an option of two ICRS.

The first ICRS would belong SHP file (for example rubberbanding SHP used for drawing a new SHP file) holding the same ICRS as SFmap. Second ICRS would belong to SHP whose vicinity is under test. Its ICRS differs from SFmap ICRS.

I tested the current implementation but it does not detect the SHP file which ICRS differs from SFmap ICRS.
However, it correctly filters relevant SHP files out.

Why is that needed?
When drawing a new SHP (polyline for example) it is normal to snap (if the snap is needed)  to another SHP that is close enough. 
This way topology is retained.
Hope this makes sense.

**Comment by wfletcher** [comment]
Sorry this doesn’t make sense to me. You are suggesting we add 2 source ICRS parameters to the method?

**Comment by dusko23** [comment]
Yes, and how it should work?
Scenario:
SFmap object is showing a raster map with ICRS_1.
At the same time, SFmap is showing SHPfile having ICRS_2.
The user is drawing a new Polyline. It has ICRS_1 and is created by clicking.
Assume that 5 points are already created by clicking the raster map.
Then user wants to SNIP the next point to SHPfile with ICRS_2.
 
The current implementation does not support that SNIP.
2 parameters ICRS would enable that, I think.
During mouse move, the GetClosestShape method compares pointD in ICRS_1 with SHPfiles holding ICRS_2.
It means that you convert PointD_ICRS_1 to PointD_ICRS_2 and seek Closeness to ICRS_2 originated SHPfies. You convert pointD_ICRS_1 to pointD_ICRS2 only once for a session, not non for every mouse move.
As soon as the diameter parameter fits the bill Record Index of a SHPfile is returned.

Sure converting the SHPfile having ICRS_2 to ICRS_1 is doable, however, it is not an elegant solution because that SHPfile can be huge.
It is all about creating new SHPfiles inside your system in multi ICRS environment.
Drawing from scratch works just great. Your animation rectangle example is a perfect proof of how Background and Foreground properties do the perfect support job for editing.
If needed I can create a video to be even more picturesque.
