### ISSUE TITLE
Swapping Fill and Outline Colours

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#63]
An interesting effect was discovered.
The thing is that when rendering Polyline the actual Polyline-Fill-Colour is based on LineType.
If Polyline LineType is set to Solid, Fill Color is taken from Outline-Color rather than Fill-Color.
This gives an interesting effect.

This is an example of an Outline LineType.

![image](https://user-images.githubusercontent.com/26789352/166674504-12c06e56-a076-47f2-aef9-3822a383d6be.png)

Changing to Solid LineType SFmap shows this. Please note Captions change in Context.

![image](https://user-images.githubusercontent.com/26789352/166674679-c4ec8ab1-7264-4702-b42c-f4c28fe4b053.png)

Swapping Outline-Color-Source to Fill-Color-Source is suggested for Solid LineType Polyline.

It is doable to swap Color positions in Context (swapping Fill and Outline Color selector. But that is a final resource.  
The question is if Rendeder logic will be changed at some point to reflect the suggestion.
If not, then I will swap positions of Color Selectors.

**Comment by wfletcher** [comment]
When polylines are rendered they are rendered twice by default- once with the outline colour and then if the line pen width is > 2 pixels a second time with the fill colour. 

If the Polyline LineType is set to Solid it is only rendered once using the outline colour.

this logic is as designed and won’t change

**Comment by dusko23** [comment]
Thanks, Winston, will update by swapping color holders at my end.
