### ISSUE TITLE
Detection Offset "Detected"

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#65]
Scanario:
The drawing quality is set to Automatic.
When Points are shown as Diamonds Detection Offset kicks in.
The red cross intersection shows the position where Point is reported as detected.
It is about 5 or so pixels offset.
![image](https://user-images.githubusercontent.com/26789352/167110378-ce561959-1d49-4af6-8314-a9fcb6a0d4e8.png)
I hope this makes sense.

**Comment by dusko23** [comment]
**Interesting Experiment**
I think there is a bug with how Point SHP Pixel Coordinate is calculated from Point Coordinate.
As well it may be that Pixel Coordinate is **calculated correctly** but Point is **rendered incorrectly.**

The image below shows:
- Polyline State Border in WHITE.
- Red Point inside State Border.
- Zoom Level is 0.5
![image](https://user-images.githubusercontent.com/26789352/168673338-b1b92d73-1dec-4e8f-82fa-058419fcc0e7.png)

Now let's Zoom Out and observe how Point starts moving. Zoom is 0.125
![image](https://user-images.githubusercontent.com/26789352/168673624-ee6c9476-8d40-43ed-97a5-eeaf4b9089ae.png)

Zoom is 0.03125 and Point is rendered on State Border.
![image](https://user-images.githubusercontent.com/26789352/168673907-07ef5b3b-78fe-4a2d-a746-04bd162ca339.png)

One step more. Zoom is 0.00781. The point is rendered outside State Border.
![image](https://user-images.githubusercontent.com/26789352/168674207-feaeb54f-19ea-4083-bd94-d24d0b79c48e.png)

**Please note that Polyline State Border is rendered  Correctly.**

Same example using EasyGisDotNet 4.8
![image](https://user-images.githubusercontent.com/26789352/168675095-437723e9-84b8-4d42-b672-513dc470272e.png)
![image](https://user-images.githubusercontent.com/26789352/168675199-5d8750dc-0a83-4ca8-9977-c8e5ed970eee.png)

**It would be really great to find a solution.**

**Comment by wfletcher** [comment]
I will look into this. Are you seeing this with specific projections? If you could upload sample shapefiles this would be great

**Comment by wfletcher** [comment]
I can reproduce this with RenderSettings set to Low Quality. Note that if the RenderQuality is set to Auto it will switch to Low quality as you zoom out of the map, which is probably why you are seeing this.

I will fix this in next release, but until then you may need to set the quality to High

**Comment by wfletcher** [comment]
Issue was introduced a few versions ago and is due to Low Quality Rendering using GDI, which does not use the Graphics.Transform property.

**Comment by dusko23** [comment]
**Interesting Discovery 2**
It appears that the problem relates to the size of the SHP file.
Absolutely weird but here are two files to replicate the issue.
Both have the same prj file
[https://we.tl/t-wYanD19yFn](url)

Here how it looks like.
**Close Zoom**
![image](https://user-images.githubusercontent.com/26789352/168732057-646b0dd1-3b63-4bb4-967b-b48b49490b00.png)

**Far Zoom**
![image](https://user-images.githubusercontent.com/26789352/168732123-945f7f65-14c6-45a9-8974-d67f0edf9dcb.png)

Hope this helps.

**Comment by wfletcher** [comment]
When the render quality is set to auto it has some smarts to switch between hig and low quality, which is based on the number of records and the zoom level. Because yous small file only has a few records it is rendered using high quality. If you change the settings from auto to high the points will render in the same location for both shapefiles

**Comment by dusko23** [comment]
Thanks, I see. Any chance to make low quality to render more correctly?
Alternative:
Perhaps adding SHP rendering output parameter to "see" which Quality will be applied might help to do last-minute actions inside the Paint Background event.
Like hiding shp or setting render quality to high. Depending on the context.
I use that to render some objects proportionally when needed. Like point size or font size.
It is interesting that Polyline always renders correctly.

**Comment by wfletcher** [comment]
This issue only affected point, pointZ and multipoint shapefiles and is a bug that was introduced in version 4.7.3.1.

The issue has been fixed and is available in latest source code. Fix will be included in next release

**Comment by dusko23** [comment]
Thanks, will wait for the next release.
