### ISSUE TITLE
Text With Shadow is Displaced

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#66]
Here is an example.
Non shadowed text looks ok.
![image](https://user-images.githubusercontent.com/26789352/168501701-4e634bd4-3672-4bcb-923d-6c326f8b96fb.png)

Shadowed Text does not.
![image](https://user-images.githubusercontent.com/26789352/168501754-e0c03bf0-30eb-4661-ba16-2e56e7549997.png)

Can this be fixed?
I will be overlying glyphs to create colored icons. Left, right ear, and face (Wolf.ttf example).
Currently, only the last (topmost) glyph to be drawn is shown.

**Comment by wfletcher** [comment]
Fixed in 4.8.1

**Comment by dusko23** [comment]
THX :-)
