### ISSUE TITLE
SHP Field Name Length Limit

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#68]
I recently got a shape file where some Field Names in the DBF file are longer than 10 characters.
The library reads all data well and gives correct Field Names.

![image](https://user-images.githubusercontent.com/26789352/172341079-6f013152-c025-40cf-9e82-96e97fd4f883.png)

However, when I try to create a new SHP file (points that falls inside rectangle) based on previous DBF filles
![image](https://user-images.githubusercontent.com/26789352/172340525-7e2a838f-7940-4a13-b311-af9517c72495.png)

and error is raised.
![image](https://user-images.githubusercontent.com/26789352/172340780-3d4c88c1-d65d-4207-9ffb-f4e7d7ba063f.png)

This is an urgent message.
Please help.

**Comment by wfletcher** [comment]
The maximum length of a dbf field name is 10 characters.
https://www.dbf2002.com/dbf-file-format.html
if your input shapefile had field names longer than 10 characters then it is not a conformant DBF file.
You will need to limit your attribute field names to 10 characters when you write a shapefile

**Comment by wfletcher** [comment]
Something  seems strange with your field names. It appears that the last character of some of the names is the field type byte. N is numeric, L is logical(Boolean). Can you post a link to where the shapefile can be downloaded?

**Comment by dusko23** [comment]
[http://register.ocistimo.si/RegisterDivjihOdlagalisc/index.jsp?page=izvoz](url)
Slovene language
Click IZVOZI

**Comment by wfletcher** [comment]
I have looked into this issue and it is not a bug in EGIS - the shapefile's DBF file has an incorrect DBF header. 
The DBF file format specifies that field headers have a maximum length of 10 characters followed by a zero byte (\0). This shapefile DBF has not terminated the field names with the zero byte.

![image](https://user-images.githubusercontent.com/12992602/174193109-9bc976c1-961d-4a40-ab51-56c2171bbb04.png)

I have added a check to the EGIS DbfReader to limit field names to 10 characters; however you should still check your field names are not longer than 10 characters when you write a new shapefile
