### ISSUE TITLE
Custom Render Direction

### ISSUE THREAD

**Issue by katterfelto** [wfletcher/EasyGIS.NET#7]
We have a requirement to change the direction arrows based on the movement direction along a line rather than the drawn direction.

I have implemented this by adding a GetDirection() function to ICustomRenderSettings. The function should return 1 for drawn direction; -1 to reverse the direction arrow and 0 to not draw the direction on that line.

If you would like this I can create a pull request otherwise I will maintain is on my fork.

**Comment by wfletcher** [comment]
This sounds like a good feature, but I am a bit concerned that it will break code as ICustomRenderSettings is used quite extensively for web projects.

I am going to leave the issue open for the time being and If I get some more requests for this feature I will let you know

**Comment by wfletcher** [comment]
I'm considering adding a GetRecordLabel to the ICustomRenderSettings interface. Given this is going to be a breaking change if you would like to create a pull request I can merge your changes into master

**Comment by katterfelto** [comment]
I will try to sort it out soon. I am a bit busy at the moment, hopefully I can find time next weekend.

**Comment by wfletcher** [comment]
pull request merged, closing issue
