### ISSUE TITLE
GetBitmap Bug Not Sorted Yet or Reintroduced?

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#74]
I have created a product line to render OSM shape data and save results as a bitmap.
SFmap object is resized in runtime.
![image](https://user-images.githubusercontent.com/26789352/181996574-6ecb5d65-abb1-4dc9-bb62-9d8140d8c9f9.png)
![image](https://user-images.githubusercontent.com/26789352/181996593-e7181cbd-f6f3-4890-adf2-1ce13621f75f.png)

The thing is that the resulting bitmap is 2 pixels shorter than the declared width and height.
The declared width and height are 5000 pixels.
GetBitmap returns PNG file resolution 4998 x 4998 pixels.
I was reporting this a while ago and I think it was sorted out at some point in the library. But I am not sure.

I am not sure if increasing width and height by 2 pixels would work as expected in all cases (not knowing what is happening inside the GetBitmap function). 

The reason why I am doing it is to update existing raster maps with new raster data.

From this
![image](https://user-images.githubusercontent.com/26789352/181996831-d36ba3e8-f0c2-44a9-a366-1b20d6455c21.png)

to this
![image](https://user-images.githubusercontent.com/26789352/181996857-b0b9569f-cc26-4d73-8a2c-e4e4f4a5f63a.png)

by GetBitmap from this
![image](https://user-images.githubusercontent.com/26789352/181996884-571501b4-74dd-49a7-adca-52972cc806cd.png)

Some guidance is welcome here.

To remember:
If this is to be sorted out at some point in the library I would need to remember me to remove the shortcut cure.

Regards,
Dusan

**Comment by wfletcher** [comment]
The size of the Bitmap will be the same as SFMap.ClientSize, not SFMap.Size. ClientSize accounts for any borders that the control may be using. The 2 pixel difference is probably because your SFMap control has a BorderStyle of FixedSingle

**Comment by dusko23** [comment]
Yes, my bad :-)
FixedSingle it was.
