### ISSUE TITLE
Joining Artefacts

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#76]
Rendering huge multilayer OSM shape files does really put the SFmap library to the test.
Works very nice.
There is one thing I have spotted.
Joining flat syle start/end records produces visible artifacts.
![image](https://user-images.githubusercontent.com/26789352/182068908-dc1b7977-b286-489e-b902-a4f6fed92788.png)
It appears that the library internal joining records parameter is not set to Round.
Could this be fixed?

**Comment by wfletcher** [comment]
Looking at the source code the following pen properties are set:
                          
**gdiplusPen.EndCap = renderSettings.LineEndCap;
                            gdiplusPen.StartCap = renderSettings.LineStartCap;
                            gdiplusPen.LineJoin = System.Drawing.Drawing2D.LineJoin.Round;
                            selectPen.EndCap = renderSettings.LineEndCap;
                            selectPen.StartCap = renderSettings.LineStartCap;
                            selectPen.LineJoin = System.Drawing.Drawing2D.LineJoin.Round;
                            if (renderSettings.LineType == LineType.Solid)
                            {
                                gdiplusPen.DashStyle = renderSettings.LineDashStyle;
                                selectPen.DashStyle = renderSettings.LineDashStyle;
                            }**



Looking at your picture my only guess is that the visible artifact is between 2 separate records. My suggestion would be to try setting the RenderSettings LineEndCap and LineStartCap properties to LineCap.Round

**Comment by dusko23** [comment]
Thanks, works well now.
Because round caps produce line overshot I need to add extra sorting function in OSM layers.
WIthin OSM layer roads with higher importance need to be drawn after lower importance in order to mask that overshot.
