### ISSUE TITLE
MinPixelPenWidth

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#78]
After the successful implementation of OpenStreepMap SHP files, tweaking MinPixelPenWidth would greatly help.
This is an example where all roads are visible each renderedd in its own way.
![image](https://user-images.githubusercontent.com/26789352/187056583-e8a2d094-039c-4968-b5fc-e4614f7949f3.png)

Setting MinPixelPenWidth to either -1, 0, or 1 produces the same result.
![image](https://user-images.githubusercontent.com/26789352/187056637-7111ee13-0303-4141-b927-175b2ff2ae0a.png)

It would be just great if setting MinPixelPenWidth to either -1 or 0 would make relevant Records **Invisible**.

**Comment by wfletcher** [comment]
Have you tried using ICustomRenderSettings? You could set a ICustomRenderSettings on your shapefile RenderSettings and hide individual records with the ICustomRenderSettings.RenderShape method

**Comment by dusko23** [comment]
Currently, I try to avoid custom_renderer_settings because it does not expose all renderer settings.
I am also not sure how to create custom_rendeder_setting in runtime.
Setting minimum width to 0 or a negative value is an excellent candidate to look at things because a value of 0 or a negative one strongly indicates that record should not be visible :-)

**Comment by wfletcher** [comment]
I think you’re missing the point of using ICustomRenderSettings. All the properties of RenderSettings are used and if you set an ICustomRenderSettings object you can override the behaviour such as whether to render a record

**Comment by dusko23** [comment]
Thanks for clearing this up.
I have looked here
![image](https://user-images.githubusercontent.com/26789352/188334538-a74c025c-3d38-4a2d-abb8-f6464f8005ff.png)
and somehow concluded that only those properties can be set as Custom Renderer Properties :-)

RenderShape actually addresses Rendering a Record and not a Shape(file). I understand now that Shape = Single Record in your library. For some users that might be misleading at the beginning because Shape brings a ShapeFile into perception.

I am not sure how to use the RenderShape method NOT to render a record (make it invisible) when the pixel size is greater than the specified value (or smaller than the specified zoom). That is the idea of setting MinPixelPenWidth to -1 or 0.

A tip on how to create IcustomRendederSettings in runtime would be great. I have never done overriding in runtime.

**Comment by wfletcher** [comment]
I have added a Visible property to the RenderSettings class to enable hiding a layer without removing it from the map.

If you want more control here is sample ICustomRenderSettings code
```

public class ExampleCustomRenderSettings : EGIS.ShapeFileLib.BaseCustomRenderSettings
	{
		public ExampleCustomRenderSettings(EGIS.ShapeFileLib.RenderSettings settings)
			:base(settings)
		{
		}

		public override bool RenderShape(int recordNumber)
		{
			//render every second record
			return recordNumber % 2 == 0;

			//add logic here to control whether a record shouold be rendered
			//examples:
			//- reference to a map zoom level?
			//- based on an attribute
			//	renderSettings.DbfReader.GetFields(recordNumber)[fieldIndex] == "blah"
		}
	}

//set on a shapefile's RenderSettings 
shapeFile..RenderSettings.CustomRenderSettings = new ExampleCustomRenderSettings(shapeFile.RenderSettings);

```
