### ISSUE TITLE
Unable to load DLL 'proj_9_0.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by theo2f** [wfletcher/EasyGIS.NET#79]
Hi guys.
I'm in troubble doing a update on a customer.
On my PC the app is working fine. Running well with customer shapefiles. But when I ran on the customer environment, the app crashed on load proj_9_0.dll.
A version of my app that's working on my PC was copied to customer server (Windows Server 2012). Did not work.
I tryed to copy to another PC (Windows 10). Did not work.
DotNet Framework reinstalled. Did not work.

I'm working on this for all day, but I can't find what's wrong.
Someone here already passed by this problem?

![image](https://user-images.githubusercontent.com/5304192/187793996-87411bf6-3d83-438e-8e27-19657b7a02db.png)
![image](https://user-images.githubusercontent.com/5304192/187794185-9e19ea0d-6b61-4a36-96aa-4470a6ec779e.png)

> The type initializer for 'EGIS.Projections.Proj6Native' threw an exception.
> Message (StackTrace):    at EGIS.Projections.Proj6Native.Proj_get_codes_from_database(IntPtr ctx, String auth_name, PJ_TYPE type, Int32 allow_deprecated)
>    at EGIS.Projections.CoordinateReferenceSystemFactory.LoadDataFromDatabase() in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.Projections\CoordinateReferenceSystemFactory.cs:line 335
>    at EGIS.Projections.CoordinateReferenceSystemFactory.LoadData() in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.Projections\CoordinateReferenceSystemFactory.cs:line 187
>    at EGIS.Projections.CoordinateReferenceSystemFactory.get_Default() in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.Projections\CoordinateReferenceSystemFactory.cs:line 98
>    at EGIS.ShapeFileLib.ShapeFile.set_ProjectionWKT(String value) in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.ShapeFileLib\ShapeFile.cs:line 262
>    at EGIS.ShapeFileLib.ShapeFile.ReadProjection(Stream prjStream) in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.ShapeFileLib\ShapeFile.cs:line 1241
>    at EGIS.ShapeFileLib.ShapeFile.ReadPrjFile(String shapeFilePath) in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.ShapeFileLib\ShapeFile.cs:line 1228
>    at EGIS.ShapeFileLib.ShapeFile.LoadFromFile(String shapeFilePath, Boolean useMemoryStreams) in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.ShapeFileLib\ShapeFile.cs:line 1153
>    at EGIS.Controls.SFMap.OpenShapeFile(String path, String name, String renderFieldName, Boolean useMemoryStreams, LayerPositionEnum layerPosition) in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.Controls\SFMap.cs:line 1581
>    at EGIS.Controls.SFMap.AddShapeFile(String path, String name, String labelFieldName, Boolean useMemoryStreams, Boolean fitMapToLayerExtent, Boolean refreshImmediately, LayerPositionEnum layerPosition) in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.Controls\SFMap.cs:line 1230
>    at [MY PROJECT].Forms.CadShape.txtArquivo_TextChanged(Object sender, EventArgs e) in C:\Projetos\\[MY PROJECT]\branches\2.0\Forms\CadShape.cs:line 386
>    at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
>    at System.Windows.Forms.Control.set_Text(String value)
>    at System.Windows.Forms.TextBoxBase.set_Text(String value)
>    at System.Windows.Forms.TextBox.set_Text(String value)
>    at [MY PROJECT].Forms.CadShape.PopulaFormulario(shape _t) in C:\Projetos\\[MY PROJECT]\branches\2.0\Forms\CadShape.cs:line 202
>    at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
>    at System.Windows.Forms.DataGridView.FlushSelectionChanged()
>    at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
>    at System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
>    at System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
>    at System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
>    at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
>    at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
>    at System.Windows.Forms.DataGridViewRowCollection.AddInternal(DataGridViewRow dataGridViewRow)
>    at System.Windows.Forms.DataGridView.RefreshRows(Boolean scrollIntoView)
>    at System.Windows.Forms.DataGridView.OnBindingContextChanged(EventArgs e)
>    at System.Windows.Forms.Control.OnParentBindingContextChanged(EventArgs e)
>    at System.Windows.Forms.Control.OnBindingContextChanged(EventArgs e)
>    at System.Windows.Forms.Control.OnParentBindingContextChanged(EventArgs e)
>    at System.Windows.Forms.Control.OnBindingContextChanged(EventArgs e)
>    at System.Windows.Forms.Control.OnParentBindingContextChanged(EventArgs e)
>    at System.Windows.Forms.Control.OnBindingContextChanged(EventArgs e)
>    at System.Windows.Forms.Control.set_BindingContextInternal(BindingContext value)
>    at System.Windows.Forms.ContainerControl.set_BindingContext(BindingContext value)
>    at System.Windows.Forms.ContainerControl.get_BindingContext()
>    at System.Windows.Forms.Control.get_BindingContextInternal()
>    at System.Windows.Forms.Control.get_BindingContextInternal()
>    at System.Windows.Forms.Control.get_BindingContextInternal()
>    at System.Windows.Forms.DataGridView.DataGridViewDataConnection.SetDataConnection(Object dataSource, String dataMember)
>    at System.Windows.Forms.DataGridView.set_DataSource(Object value)
>    at [MY PROJECT].Forms.CadShape.PopulaLista() in C:\Projetos\\[MY PROJECT]\branches\2.0\Forms\CadShape.cs:line 184
>    at [MY PROJECT].Forms.CadShape.CadastroShape_Load(Object sender, EventArgs e) in C:\Projetos\\[MY PROJECT]\branches\2.0\Forms\CadShape.cs:line 30
>    at System.Windows.Forms.Form.OnLoad(EventArgs e)
>    at System.Windows.Forms.Form.OnCreateControl()
>    at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    at System.Windows.Forms.Control.CreateControl()
>    at System.Windows.Forms.Control.WmShowWindow(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Form.WmShowWindow(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> **Inner Exception Message: Unable to load DLL 'proj_9_0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)**
> Inner Exception Message (StackTrace):    at EGIS.Projections.Proj6Native.proj_context_set_database_path(IntPtr ctx, String dbPath, String auxDbPaths, String options)
>    at EGIS.Projections.Proj6Native..cctor() in C:\Projetos\\[MY PROJECT]\branches\Apoio\EGIS.Projections\Proj6Native.cs:line 94

**Comment by theo2f** [comment]
Oh God! What a stupid mistake of mine!

![image](https://user-images.githubusercontent.com/5304192/187806451-c8527a01-b90f-4c75-83f0-fc752956c7ff.png)

**Comment by wfletcher** [comment]
Sorry didn’t reply sooner but looks like you found what I was going to suggest

**Comment by theo2f** [comment]
You have already given the solution. I didn't pay attention.
Thanks!

**Comment by vergo77** [comment]
Hello all,
I'know this issue is closed, but I'm facing on the same issue, on my computer it runs, on a second one it wont run.
Yes, the Microsoft Visual C++ Redistributable for Visual Studio 2019 is installed...

Can some one help me?
Thanks
