### ISSUE TITLE
C# Timer Enable Auto transform to false

### ISSUE THREAD

**Issue by AliexChang** [wfletcher/EasyGIS.NET#80]
When i use sfMap1_Paint function , always the other Timer enable auto transform to false , but can't trick enable to true.

My timer_trick is get SystemTime ( Lab_Systime.Text = DateTime.Now.TimeOfDay.ToString();  )

please help to solve

**Comment by wfletcher** [comment]
Sorry don’t understand your issue. Can you please elaborate or post some sample code
