### ISSUE TITLE
Can  EasyGIS Load the other file?

### ISSUE THREAD

**Issue by AliexChang** [wfletcher/EasyGIS.NET#81]
Now EasyGIS can load .shp ~^^~

can load the other files?

ex:

tif,bmp...?

because i want to see beautiful map (like google),in my EasyGis ~

or how to load other file~? Thank for Ans~!

**Comment by wfletcher** [comment]
Sorry the library only supports shapefiles of loading images from tile servers. Unless you are going to run your own local tile server it’s shapefiles only without an internet connection

**Comment by AliexChang** [comment]
Thnak u for Ans~!
