### ISSUE TITLE
Example 1 

### ISSUE THREAD

**Issue by AliexChang** [wfletcher/EasyGIS.NET#82]
When i run to Example 1 ,  beside red line see yellow object ?
(that can show  record:XX message)

but i can't find that in all code , anyone can help?

**Comment by wfletcher** [comment]
I assume that you are referring to the tooltip that is displayed when the mouse moves over a shape record.

```
 sf.RenderSettings.UseToolTip = true;
 sf.RenderSettings.ToolTipFieldName = sf.RenderSettings.FieldName;
```

You need to set .RenderSettings.ToolTipFieldName to the name of one of the ShapeFile attribute field names

**Comment by AliexChang** [comment]
Thank u for Ans , now i can use it ~!
