### ISSUE TITLE
Web Demo Files Ignored

### ISSUE THREAD

**Issue by katterfelto** [wfletcher/EasyGIS.NET#9]
I have just tried to run the web demo from a clone of the repository. There are a lot of files missing from the demos folder.

I think the issue lies with the gitignore file. I'm not sure how to add exceptions for file types for specific folders but I think that would allow you to commit all the required files.

I have an older copy so could restore them. The following is the list of the files currently missing from the repo:

```
demo2.egp
demo2_files/
us_demo.egp
us_demo_files/cities.dbf
us_demo_files/cities.shp
us_demo_files/cities.shx
us_demo_files/counties.dbf
us_demo_files/counties.shp
us_demo_files/counties.shx
us_demo_files/lakes.dbf
us_demo_files/lakes.shp
us_demo_files/lakes.shx
us_demo_files/states.dbf
us_demo_files/states.shp
us_demo_files/states.shx
world.egp
world_files/world_adm0.dbf
world_files/world_adm0.shp
world_files/world_adm0.shx

**Comment by wfletcher** [comment]
Thanks for reporting this. I’ll check and push the missing files up tomorrow.
